insert into ShelfLocations (Section, Floor) values ('Health Care', 4);
insert into ShelfLocations (Section, Floor) values ('n/a', 4);
insert into ShelfLocations (Section, Floor) values ('n/a', 3);
insert into ShelfLocations (Section, Floor) values ('Finance', 4);
insert into ShelfLocations (Section, Floor) values ('Capital Goods', 3);
insert into ShelfLocations (Section, Floor) values ('Finance', 2);
insert into ShelfLocations (Section, Floor) values ('Basic Industries', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 1);
insert into ShelfLocations (Section, Floor) values ('Technology', 1);
insert into ShelfLocations (Section, Floor) values ('Public Utilities', 3);
insert into ShelfLocations (Section, Floor) values ('Energy', 1);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('n/a', 1);
insert into ShelfLocations (Section, Floor) values ('n/a', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 3);
insert into ShelfLocations (Section, Floor) values ('Capital Goods', 4);
insert into ShelfLocations (Section, Floor) values ('Health Care', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 1);
insert into ShelfLocations (Section, Floor) values ('Capital Goods', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 4);
insert into ShelfLocations (Section, Floor) values ('Miscellaneous', 2);
insert into ShelfLocations (Section, Floor) values ('Capital Goods', 3);
insert into ShelfLocations (Section, Floor) values ('n/a', 3);
insert into ShelfLocations (Section, Floor) values ('Finance', 2);
insert into ShelfLocations (Section, Floor) values ('Basic Industries', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 2);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 1);
insert into ShelfLocations (Section, Floor) values ('Technology', 1);
insert into ShelfLocations (Section, Floor) values ('Capital Goods', 4);
insert into ShelfLocations (Section, Floor) values ('Technology', 1);
insert into ShelfLocations (Section, Floor) values ('Technology', 1);
insert into ShelfLocations (Section, Floor) values ('Miscellaneous', 1);
insert into ShelfLocations (Section, Floor) values ('Technology', 1);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 2);
insert into ShelfLocations (Section, Floor) values ('Capital Goods', 2);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 4);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 2);
insert into ShelfLocations (Section, Floor) values ('Consumer Non-Durables', 1);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 3);
insert into ShelfLocations (Section, Floor) values ('Public Utilities', 2);
insert into ShelfLocations (Section, Floor) values ('Health Care', 2);
insert into ShelfLocations (Section, Floor) values ('Health Care', 2);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 4);
insert into ShelfLocations (Section, Floor) values ('n/a', 4);
insert into ShelfLocations (Section, Floor) values ('Technology', 3);
insert into ShelfLocations (Section, Floor) values ('Transportation', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 1);
insert into ShelfLocations (Section, Floor) values ('Technology', 4);
insert into ShelfLocations (Section, Floor) values ('Public Utilities', 2);
insert into ShelfLocations (Section, Floor) values ('Health Care', 1);
insert into ShelfLocations (Section, Floor) values ('Public Utilities', 3);
insert into ShelfLocations (Section, Floor) values ('Technology', 3);
insert into ShelfLocations (Section, Floor) values ('Health Care', 1);
insert into ShelfLocations (Section, Floor) values ('Health Care', 4);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('Technology', 1);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 2);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('Health Care', 2);
insert into ShelfLocations (Section, Floor) values ('Public Utilities', 1);
insert into ShelfLocations (Section, Floor) values ('n/a', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 2);
insert into ShelfLocations (Section, Floor) values ('Finance', 1);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 2);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 3);
insert into ShelfLocations (Section, Floor) values ('Health Care', 1);
insert into ShelfLocations (Section, Floor) values ('Health Care', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Non-Durables', 1);
insert into ShelfLocations (Section, Floor) values ('n/a', 4);
insert into ShelfLocations (Section, Floor) values ('n/a', 3);
insert into ShelfLocations (Section, Floor) values ('Health Care', 4);
insert into ShelfLocations (Section, Floor) values ('n/a', 1);
insert into ShelfLocations (Section, Floor) values ('Capital Goods', 4);
insert into ShelfLocations (Section, Floor) values ('Finance', 2);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 1);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('n/a', 1);
insert into ShelfLocations (Section, Floor) values ('Transportation', 2);
insert into ShelfLocations (Section, Floor) values ('n/a', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Durables', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 1);
insert into ShelfLocations (Section, Floor) values ('n/a', 4);
insert into ShelfLocations (Section, Floor) values ('Energy', 2);
insert into ShelfLocations (Section, Floor) values ('Technology', 4);
insert into ShelfLocations (Section, Floor) values ('n/a', 2);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 1);
insert into ShelfLocations (Section, Floor) values ('Finance', 4);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 3);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('Consumer Services', 1);
insert into ShelfLocations (Section, Floor) values ('Consumer Durables', 4);
insert into ShelfLocations (Section, Floor) values ('Finance', 3);
insert into ShelfLocations (Section, Floor) values ('n/a', 1);